from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel
import uvicorn
import os

from graph import graph_app

app = FastAPI(title="Proactive Financial Agent Demo")

# Create directories if they don't exist
os.makedirs("static", exist_ok=True)
os.makedirs("templates", exist_ok=True)

app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

class AnalyzeRequest(BaseModel):
    user_id: str
    user_name: str
    age: int
    score: float
    retirement_gap: int
    monthly_income: int
    monthly_emi: int

# Render the UI
@app.get("/", response_class=HTMLResponse)
async def read_root(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

# Run the LangGraph Execution
@app.post("/api/analyze")
async def analyze_user(req: AnalyzeRequest):
    initial_state = {
        "user_id": req.user_id,
        "score": req.score,
        "user_name": req.user_name,
        "user_age": req.age,
        "retirement_gap": req.retirement_gap,
        "monthly_income": req.monthly_income,
        "monthly_emi": req.monthly_emi
    }
    
    # Invoke LangGraph
    result = graph_app.invoke(initial_state)
    
    # Return the structured data generated by the nodes
    return {
        "status": "success",
        "agent_response": result.get("agent_response", {}),
        "resilience_activities": result.get("resilience_activities", {}),
        "stability_activities": result.get("stability_activities", {}),
        "safety_net_activities": result.get("safety_net_activities", {}),
        "debt_revival_activities": result.get("debt_revival_activities", {})
    }

# Mock Endpoint: Enroll Scheme
@app.post("/api/enroll_scheme")
async def enroll_scheme():
    return {"status": "success", "message": "Successfully enrolled in PMJJBY! Policy document sent to email."}

# Mock Endpoint: Start SIP
@app.post("/api/start_sip")
async def start_sip():
    return {"status": "success", "message": "SIP of ₹5555 successfully started! Projected retirement corpus met."}

# Mock Endpoint: Top-up Cover
@app.post("/api/buy_insurance")
async def buy_insurance():
    return {"status": "success", "message": "HealthSuraksha Premium purchased successfully! Cover active."}

# Mock Endpoint: Toggle Tips
@app.post("/api/toggle_tips")
async def toggle_tips():
    return {"status": "success", "message": "Weekly financial tips via email activated!"}

# Mock Endpoint: Expense Action
@app.post("/api/expense_action")
async def expense_action():
    return {"status": "success", "message": "Action taken to optimize subscription!"}

# --- STABILITY ANCHOR MOCK ENDPOINTS ---

@app.post("/api/restructure_emi")
async def restructure_emi():
    return {"status": "success", "message": "EMI restructuring plan initiated with banking partner!"}

@app.post("/api/apply_insurance_urgent")
async def apply_insurance_urgent():
    return {"status": "success", "message": "Urgent PMJJBY application submitted successfully!"}

@app.post("/api/toggle_micro_learning")
async def toggle_micro_learning():
    return {"status": "success", "message": "Weekly debt management videos enabled."}

@app.post("/api/connect_counselor")
async def connect_counselor():
    return {"status": "success", "message": "Counselor request sent. Connecting you shortly..."}

@app.post("/api/setup_bill_reminders")
async def setup_bill_reminders():
    return {"status": "success", "message": "Bill reminders set up on your calendar!"}

@app.post("/api/enroll_budget_challenge")
async def enroll_budget_challenge():
    return {"status": "success", "message": "Successfully enrolled in the 7-day budgeting challenge!"}

# --- SAFETY NET MOCK ENDPOINTS ---

@app.post("/api/start_emergency_fund")
async def start_emergency_fund():
    return {"status": "success", "message": "Emergency fund goal created. Auto-deposit setup linked!"}

@app.post("/api/call_debt_helpline")
async def call_debt_helpline():
    return {"status": "success", "message": "Calling 1800-DEBT-HELP. Connecting to advisor... (Mock)"}

@app.post("/api/apply_welfare_scheme")
async def apply_welfare_scheme():
    return {"status": "success", "message": "Food Subsidy Program & PMGKY application filed."}

@app.post("/api/defer_payment")
async def defer_payment():
    return {"status": "success", "message": "Payment actively deferred for 30 days pending lender approval."}

# --- DEBT REVIVAL MOCK ENDPOINTS ---

@app.post("/api/start_debt_counseling")
async def start_debt_counseling():
    return {"status": "success", "message": "Debt counselor chat session initiated. Welcome!"}

@app.post("/api/apply_ots")
async def apply_ots():
    return {"status": "success", "message": "One Time Settlement (OTS) offer submitted to the bank."}

@app.post("/api/apply_emergency_ration")
async def apply_emergency_ration():
    return {"status": "success", "message": "Urgent emergency ration request sent directly to block officer."}

@app.post("/api/consolidate_debt")
async def consolidate_debt():
    return {"status": "success", "message": "Debt consolidation proposal drafted and sent for review."}

if __name__ == "__main__":
    print("Starting Proactive Agent Server on http://localhost:8000")
    uvicorn.run(app, host="0.0.0.0", port=8000)
